// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDikFw3L7JmreN0jG5XTWsJJ5fSGZtLfY',
    appId: '1:881111050780:web:d11daef393c297be128dd9',
    messagingSenderId: '881111050780',
    projectId: 'flutter-13e36',
    authDomain: 'flutter-13e36.firebaseapp.com',
    storageBucket: 'flutter-13e36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJoTRevTH5VzcfTRqAiYMR6zo8A6CsVg',
    appId: '1:881111050780:android:b0d1e89481d37da9128dd9',
    messagingSenderId: '881111050780',
    projectId: 'flutter-13e36',
    storageBucket: 'flutter-13e36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnFWrHYufBtmUobeXvRIbnz_YCp3qQSIo',
    appId: '1:881111050780:ios:cde320596dc7a2e0128dd9',
    messagingSenderId: '881111050780',
    projectId: 'flutter-13e36',
    storageBucket: 'flutter-13e36.appspot.com',
    iosClientId: '881111050780-cbas6m57b9cg8n02fkog8em80ce5cv94.apps.googleusercontent.com',
    iosBundleId: 'com.cours.coursFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnFWrHYufBtmUobeXvRIbnz_YCp3qQSIo',
    appId: '1:881111050780:ios:d69dd077c7794f4f128dd9',
    messagingSenderId: '881111050780',
    projectId: 'flutter-13e36',
    storageBucket: 'flutter-13e36.appspot.com',
    iosClientId: '881111050780-2as3gko5007cf13g75dturn7jrnic3ij.apps.googleusercontent.com',
    iosBundleId: 'com.cours.coursFlutter.RunnerTests',
  );
}
